# 100 numpy exercises with hint

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercices for those who teach.


#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [3]:
print(np.__version__)
print(np.show_config)

1.15.1
<function show at 0x00000261198F4048>


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [6]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [9]:
a = np.array([1,2,3,4,5])
print (a.size)
print (a.itemsize)

5
4


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [11]:
np.info('add')

     *** Found in numpy ***
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [12]:
vector = np.zeros(10)
vector[4] = 1;
print (vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [15]:
arrayten_to_fifty = np.arange(10,50,1)
print (arrayten_to_fifty)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [31]:
a = np.arange(1,10,1)
i = 0
global b
for c in range(len(a)):
    i = -(c+1)
    b.append(a[i]) 
print(b)


[9, 8, 7, 6, 5, 4, 3, 2, 1, 9, 8, 7, 6, 5, 4, 3, 2, 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [32]:
line = np.array([0,1,2,3,4,5,6,7,8])
print(line.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [33]:
non_zero = np.array([1,2,0,0,4,0])
print (np.nonzero(non_zero))

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [34]:
iden3x3 = np.eye(3,3)
print (iden3x3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [37]:
ran3x3x3 = np.random.random(27)
ran3x3x3 = ran3x3x3.reshape(3,3,3)
ran3x3x3

array([[[0.21812881, 0.5703088 , 0.11158689],
        [0.77888469, 0.34526303, 0.88313445],
        [0.75329907, 0.12257991, 0.845043  ]],

       [[0.66733828, 0.58506903, 0.1965769 ],
        [0.57756107, 0.52021718, 0.50720047],
        [0.46313531, 0.40492668, 0.34591385]],

       [[0.63641109, 0.33604294, 0.46663224],
        [0.55876896, 0.69858093, 0.30015429],
        [0.60934072, 0.71376805, 0.24370947]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [38]:
ran10x10 = np.random.random(100)
ran10x10 = ran10x10.reshape(10,10)
print (ran10x10.min())
print (ran10x10.max())

0.000709312597908407
0.9987434166615934


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [40]:
rand30 = np.random.random(30)
print (rand30)
print(rand30.mean())

[0.1276457  0.56981617 0.43781538 0.60198444 0.03739161 0.38684501
 0.91524173 0.64412995 0.62176935 0.07582424 0.76695166 0.42409723
 0.34782113 0.99098671 0.53018834 0.08887034 0.13989034 0.85125179
 0.18251599 0.0543387  0.69041647 0.62074526 0.88791441 0.16097601
 0.93041625 0.9103406  0.18522135 0.75066374 0.989885   0.03294459]
0.49849664952117423


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [45]:
arr_2d = np.array([2,2,2,2,3,3,3,3,4,4,4,4,1,1,1,1]).reshape(4,4)
print (arr_2d)
print (arr_2d[1:-1,1:-1])
arr_2d[1:-1,1:-1] = [[0,0],[0,0]]
print (arr_2d)

[[2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [1 1 1 1]]
[[3 3]
 [4 4]]
[[2 2 2 2]
 [3 0 0 3]
 [4 0 0 4]
 [1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [49]:
padding = np.array([[1,2],[3,4]])
padding =  np.pad(padding,(1),'constant',constant_values=(0))
padding

array([[0, 0, 0, 0],
       [0, 1, 2, 0],
       [0, 3, 4, 0],
       [0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [8]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan

0.3 == 3* 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [11]:
np.diag([1,2,3,4],1)

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [83]:
arr8x8 = np.zeros(64).reshape(8,8)
arr8x8[::2] = 1
arr8x8[::2,::2] = 0
arr8x8[1::2,::2] = 1

arr8x8

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [32]:
a = np.zeros(6,7,8)
np.unravel_index([100],(6,7,8),order='C')

TypeError: data type not understood

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [33]:
checkerBoard1 = np.tile(np.array([1,0]),4)
checkerBoard2 = np.tile(np.array([0,1]),4)
checkerBoard = np.append(checkerBoard1,checkerBoard2,axis =0)
checkerBoard = np.tile(checkerBoard,4)
checkerBoard.reshape(8,8)
#checkerBoard


array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [38]:
ran = np.random.random(25)
print (ran)
max = ran.max()
min = ran.min()
print ("min {$0} max {$1}",min,max)
(ran - min) / (max-min)


[0.93300835 0.37267684 0.57512206 0.23650729 0.92516969 0.02188702
 0.89159    0.02429625 0.63377138 0.35268321 0.75320426 0.82497287
 0.52486769 0.94456246 0.32392007 0.18593747 0.89321964 0.80790345
 0.37893479 0.11735658 0.77006738 0.67039251 0.78185149 0.70640699
 0.99785793]
min {$0} max {$1} 0.021887023377093695 0.9978579330142907


array([0.93355378, 0.35942651, 0.56685607, 0.21990437, 0.92552212,
       0.        , 0.89111567, 0.00246855, 0.62694938, 0.33894062,
       0.74932278, 0.82285839, 0.5153644 , 0.94539236, 0.30946931,
       0.16808948, 0.89278544, 0.8053687 , 0.36583854, 0.09782009,
       0.76660109, 0.66447215, 0.77867533, 0.70137333, 1.        ])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [39]:
colors = np.array(['RGBA','RBGA','RGBA'])
print (colors.dtype)

<U4


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [40]:
arr5x3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]).reshape(5,3)
arr3x2 = np.array([1,2,3,4,5,6]).reshape(3,2)
np.dot(arr5x3,arr3x2)

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100],
       [103, 136],
       [130, 172]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [58]:
tenArray = np.array([1,2,3,4,5,6,7,8,9,10])
newarray = list(map(lambda x: x if (x<3 or x>8) else -x,tenArray))

print (newarray)




[1, 2, -3, -4, -5, -6, -7, -8, 9, 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [59]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

print (range(5))

10
10
range(0, 5)


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [71]:
Z = np.array([1,2,3,4,5])
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
#Z<Z>Z is not legal


array([1., 2., 3., 4., 5.])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [75]:
print (np.nan)
np.array([np.nan]).astype(int).astype(float)


nan


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [80]:
small_square = np.ones(4).reshape(2,2)
print(small_square)
np.ceil(small_square)

[[1. 1.]
 [1. 1.]]


array([[1., 1.],
       [1., 1.]])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [81]:
a = np.array([2,3,4,5])
b = np.array([3,4,5,6,7])
np.intersect1d(a,b)

array([3, 4, 5])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [84]:
np.seterr()
np.errstate

numpy.core.numeric.errstate

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [85]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [90]:
print (np.datetime64('today','D'))
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
print (yesterday)
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')
print (tomorrow)

2020-01-16
2020-01-15
2020-01-17


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [101]:
np.arange('2016-07','2016-08',dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [102]:
A = np.array([1,2])
B = np.array([2,3])
np.multiply(np.add(A,B), np.divide(np.negative(A),2))


array([-1.5, -5. ])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [110]:
ran = np.random.random(5)
np.floor(ran)
np.ceil(ran)
ran.astype('int')
ran = np.trunc(ran)
print (ran)

[0. 0. 0. 0. 0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [8]:
np.arange(0,4,0.16).reshape(5,5)

array([[0.  , 0.16, 0.32, 0.48, 0.64],
       [0.8 , 0.96, 1.12, 1.28, 1.44],
       [1.6 , 1.76, 1.92, 2.08, 2.24],
       [2.4 , 2.56, 2.72, 2.88, 3.04],
       [3.2 , 3.36, 3.52, 3.68, 3.84]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [19]:
my_list = [0,2,4, 0,2,4,0,2,4,3] 
it = iter(my_list)
np.fromiter(it,dtype = int)

array([0, 2, 4, 0, 2, 4, 0, 2, 4, 3])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [20]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [29]:
vector = np.random.random(10)
print(vector)
vector.sort()
vector

[0.42389608 0.75283426 0.32974195 0.60188343 0.07764551 0.1050975
 0.71604089 0.47400728 0.52634484 0.25449122]


array([0.07764551, 0.1050975 , 0.25449122, 0.32974195, 0.42389608,
       0.47400728, 0.52634484, 0.60188343, 0.71604089, 0.75283426])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [30]:
A = np.array([2,3,5,6])
np.add.reduce(A)



16

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [32]:
a = np.random.random(5)
b = np.random.random(5)
np.array_equal(a,b)
np.allclose(a,b)

False

#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [2]:
a = np.array([2,4,5])
a.flags.writeable = False
a[0] = 1


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [8]:
a = np.random.random(20).reshape(10,2)
x,y = a[:,0],a[:,1]
print (a)
print (x)
print (y)
m = np.sqrt(x**2 + y**2)
n = np.arctan2(y,x)
print ("Pythogorus Theorem ",m)
print ("Tan Theta", n)

[[0.69600147 0.92510832]
 [0.05349831 0.42956583]
 [0.31893109 0.42114295]
 [0.75688363 0.38509472]
 [0.54749255 0.729728  ]
 [0.95088991 0.32808046]
 [0.53368894 0.05807367]
 [0.60294092 0.06478755]
 [0.44097006 0.52177833]
 [0.78766214 0.03465456]]
[0.69600147 0.05349831 0.31893109 0.75688363 0.54749255 0.95088991
 0.53368894 0.60294092 0.44097006 0.78766214]
[0.92510832 0.42956583 0.42114295 0.38509472 0.729728   0.32808046
 0.05807367 0.06478755 0.52177833 0.03465456]
Pythogorus Theorem  [1.15768884 0.43288436 0.52827874 0.84921775 0.91227794 1.00589682
 0.53683931 0.60641173 0.68315974 0.78842411]
Tan Theta [0.92579552 1.44689387 0.92264026 0.47065475 0.92712286 0.33223558
 0.10838912 0.10704186 0.86913687 0.04396838]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [29]:
a = np.random.random(10)
print(a)
print (np.argmax(a))
a[np.argmax(a)] = 0
print (a)


[0.06545659 0.83337458 0.04892194 0.03383489 0.01802492 0.99623099
 0.89125765 0.53942172 0.48285467 0.97360608]
5
[0.06545659 0.83337458 0.04892194 0.03383489 0.01802492 0.
 0.89125765 0.53942172 0.48285467 0.97360608]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [30]:
x = np.array([0,1])
y = np.array([0,1])
x_1,y_1 = np.meshgrid(x,y)
print (x_1)
print (y_1)

[[0 1]
 [0 1]]
[[0 0]
 [1 1]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [31]:
x = np.array([1,2,3,4])
y = np.array([2,3,4,1])

1.0/np.subtract.outer(x, y)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.


array([[-1.        , -0.5       , -0.33333333,         inf],
       [        inf, -1.        , -0.5       ,  1.        ],
       [ 1.        ,         inf, -1.        ,  0.5       ],
       [ 0.5       ,  1.        ,         inf,  0.33333333]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [35]:
for dtype in [np.int32, np.int64, np.int8]:
    print (dtype)
    print (np.iinfo(dtype).min)
    print (np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print (dtype)
    print (np.finfo(dtype).min)
    print (np.finfo(dtype).max)
    print (np.finfo(dtype).eps)

<class 'numpy.int32'>
-2147483648
2147483647
<class 'numpy.int64'>
-9223372036854775808
9223372036854775807
<class 'numpy.int8'>
-128
127
<class 'numpy.float32'>
-3.4028235e+38
3.4028235e+38
1.1920929e-07
<class 'numpy.float64'>
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [42]:
np.set_printoptions(threshold=np.nan)
a = np.ones((25,25))
print (a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [43]:
a = np.array([7,8,5,3])
a.argmin()

Z = np.arange(100)
print (Z)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

97


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
a = 

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [41]:
np.sqrt

<ufunc 'sqrt'>

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [49]:
floatnumbers  = np.array([2.4,3.5,4.7,5.3,6.1],dtype=np.float32)
print (floatnumbers)

intnumbers = floatnumbers.astype(np.int32)
intnumbers

[2.4 3.5 4.7 5.3 6.1]


array([2, 3, 4, 5, 6])

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [54]:
np.genfromtxt("data_file.txt", delimiter=',')

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [56]:
serial = np.arange(20).reshape(4,5)
for index,x in np.ndenumerate(serial):
    print ("index -> ",index," Value -> ",x)

index ->  (0, 0)  Value ->  0
index ->  (0, 1)  Value ->  1
index ->  (0, 2)  Value ->  2
index ->  (0, 3)  Value ->  3
index ->  (0, 4)  Value ->  4
index ->  (1, 0)  Value ->  5
index ->  (1, 1)  Value ->  6
index ->  (1, 2)  Value ->  7
index ->  (1, 3)  Value ->  8
index ->  (1, 4)  Value ->  9
index ->  (2, 0)  Value ->  10
index ->  (2, 1)  Value ->  11
index ->  (2, 2)  Value ->  12
index ->  (2, 3)  Value ->  13
index ->  (2, 4)  Value ->  14
index ->  (3, 0)  Value ->  15
index ->  (3, 1)  Value ->  16
index ->  (3, 2)  Value ->  17
index ->  (3, 3)  Value ->  18
index ->  (3, 4)  Value ->  19


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [58]:
a = np.array([2,3,4])
b = np.array([8,9,10])
x, y  = np.meshgrid(a,b)
print (x)
print (y)

[[2 3 4]
 [2 3 4]
 [2 3 4]]
[[ 8  8  8]
 [ 9  9  9]
 [10 10 10]]


#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [81]:
A = np.arange(50).reshape(5,10)
print(A)
np.put(A,np.random.choice(range(40),5,replace=False),1)
A

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  1],
       [ 1, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 1, 21, 22,  1, 24, 25, 26, 27, 28, 29],
       [ 1, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [85]:
A = np.arange(20).reshape(5,4)
A - A.mean(axis=1,keepdims=1)

array([[-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [86]:
np.argsort(A)

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int64)

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [93]:
print(A)
A[:,1] = np.nan
print (A)
np.any(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[          0 -2147483648           2           3]
 [          4 -2147483648           6           7]
 [          8 -2147483648          10          11]
 [         12 -2147483648          14          15]
 [         16 -2147483648          18          19]]


True

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [97]:
np.abs(A).min()
#np.argmin(A, axis=0)

-2147483648

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [105]:
A = np.arange(3).reshape(1,3)
B = np.arange(3).reshape(3,1)
add = 0;
for i in np.nditer(A.T):
    add = add+i
   # print (i)
for i in np.nditer(B):
    add = add+i
   # print (i)
print (add)


6


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [106]:
def array():
    name = "array_name"


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)